### ISSUE TITLE
Does exist a Project example?

### ISSUE THREAD

**Issue by jabrena** [Valkryst/V2DSprite#1]
Hi, I would like to test the library but I didnt see any example project.

Many thanks in advance

Juan Antonio

**Comment by Valkryst** [comment]
Hey,

The example project for this library has been laying around on my hard drive for a few months. It's unfinished, but it does have enough written to show you how to use this library.

I've attached the example project to this comment, hopefully it helps!

[V2DSpaceInvaders.zip](https://github.com/Valkryst/V2DSprite/files/2569492/V2DSpaceInvaders.zip)

**Comment by jabrena** [comment]
Many thanks, I will review next week.

Cheers

Juan Antonio
